export const API_BASE_URL = 'http://localhost:5100/api'

export const ROLE_ENDPOINT = '/role'
export const USER_ENDPOINT = '/user'
export const IS_CONNECTED_ENDPOINT = '/user/isconnected'
export const LOGIN_ENDPOINT = '/auth/login'
export const REGISTER_ENDPOINT = '/auth/signup'
export const LOGOUT_ENDPOINT = '/auth/logout'
export const REFRESH_ENDPOINT = '/auth/refresh'

export const PROJECT_ENDPOINT = '/project'
export const ISSUE_ENDPOINT = '/issue'
export const ISSUE_STATUS_ENDPOINT = '/issue-status'
export const ISSUE_KIND_ENDPOINT = '/issue-kind'
export const ISSUE_PRIORITY_ENDPOINT = '/issue-priority'
